CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, token TEXT UNIQUE, name TEXT, avatar_url TEXT, created_at INTEGER);
CREATE TABLE IF NOT EXISTS profiles (user_id INTEGER UNIQUE, coins INTEGER DEFAULT 0, mmr INTEGER DEFAULT 1000, wins INTEGER DEFAULT 0, losses INTEGER DEFAULT 0, FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS decks (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER, name TEXT, cards_json TEXT, FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS matches (id INTEGER PRIMARY KEY AUTOINCREMENT, created_at INTEGER, ended_at INTEGER, p1_id INTEGER, p2_id INTEGER, winner_id INTEGER, duration_sec INTEGER, p1_mmr_delta INTEGER, p2_mmr_delta INTEGER, FOREIGN KEY(p1_id) REFERENCES users(id), FOREIGN KEY(p2_id) REFERENCES users(id), FOREIGN KEY(winner_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS quests (user_id INTEGER, date_utc TEXT, data_json TEXT, PRIMARY KEY(user_id,date_utc), FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS purchases (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER, item_id TEXT, created_at INTEGER, FOREIGN KEY(user_id) REFERENCES users(id));
