const express=require('express')
const http=require('http')
const {Server}=require('socket.io')
const path=require('path')
const dotenv=require('dotenv')
require('./db')
dotenv.config()
const app=express()
const server=http.createServer(app)
const io=new Server(server)
app.use(express.static(path.join(__dirname,'..','public')))
io.on('connection',socket=>{})
const port=process.env.PORT||3000
server.listen(port)
